version: '3.8'

services:
  api:
    image: minhdangpy134/gold_api_docker:latest
    env_file:
      - .env
    environment:
      - ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: uvicorn src.posts.main:app --host 0.0.0.0 --port 8000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bridge_network
