version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - ENV=docker
      - DATABASE_URL=postgresql+psycopg2://minhdangpy134:minhdang@db:5432/gold_price
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      sh -c "python -m uvicorn src.posts.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
    - db
    - redis
    restart: always
    networks:
      - bridge_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=minhdangpy134
      - POSTGRES_PASSWORD=minhdang
      - POSTGRES_DB=gold_price
    ports:
      - "5432:5432"
    restart: always
    networks:
      - bridge_network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - bridge_network

volumes:
  postgres_data:
  redis_data:

networks:
  bridge_network:
    driver: bridge 